apiVersion: apps/v1
kind: Deployment
metadata:
name: demo-ui
spec:
replicas: 1
revisionHistoryLimit: 3
selector:
matchLabels:
app: demo-ui
template:
metadata:
labels:
app: demo-ui
spec:
containers:
- image: gabrielle20/demo-ui:2fa8329b6b9e28daa8828388a007382f7961da76
name: demo-ui
ports:
- containerPort: 80
